In [3]:
#question1:moving avg
import numpy as np

In [5]:
def movingavg(inputvalue,k):
    op=np.convolve(inputvalue,np.ones(k),mode='valid')/k
    for i in op:
        print(i)

In [6]:
inputvalue = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k = 3
movingavg(inputvalue, k)

5.0
4.666666666666667
5.666666666666667
6.666666666666667
9.666666666666666
28.666666666666668
49.333333333333336
72.66666666666667
84.0
93.33333333333333
116.33333333333333


In [7]:
np.convolve(inputvalue,np.ones(k))

array([  3.,   8.,  15.,  14.,  17.,  20.,  29.,  86., 148., 218., 252.,
       280., 349., 250., 150.])

In [8]:
np.convolve(inputvalue,np.ones(k),mode='valid')

array([ 15.,  14.,  17.,  20.,  29.,  86., 148., 218., 252., 280., 349.])

# assignment question 2:


In [10]:
inputvec=np.array([1,3,5,7,9])
n=5

In [11]:
def matcreate(inputvec,n,increasing=False):
    if increasing:
        mat=np.matrix([x**i for x in inputvec for i in range(5)]).reshape(inputvec.size,n)
    else:
        mat=np.matrix([x**(n-i-1) for x in inputvec for i in range(5)]).reshape(inputvec.size,n)
    return mat

In [12]:
matcreate(inputvec,n,False)

matrix([[   1,    1,    1,    1,    1],
        [  81,   27,    9,    3,    1],
        [ 625,  125,   25,    5,    1],
        [2401,  343,   49,    7,    1],
        [6561,  729,   81,    9,    1]])

In [13]:
matcreate(inputvec,n,True)

matrix([[   1,    1,    1,    1,    1],
        [   1,    3,    9,   27,   81],
        [   1,    5,   25,  125,  625],
        [   1,    7,   49,  343, 2401],
        [   1,    9,   81,  729, 6561]])